### ISSUE TITLE
Monkey patch is not useful in current version (tensorpack 0.8.5, TensorFlow 1.3.0)

### ISSUE THREAD

**Issue by csyhhu** [czhu95/ternarynet#6]
Hi Chenzhuo, @czhu95 

The monkey-patch way to replace tf.get_variable is not useful in current version (tensorpack 0.8.5, TensorFlow 1.3.0). Codes can not generate Wn and Wp under above-mentioned platform.

Best regards,
Shangyu

**Comment by ppwwyyxx** [comment]
I've included a working implementation of TTQ inside tensorpack: https://github.com/ppwwyyxx/tensorpack/blob/b5b22a8526ae0004a95aacb3c846789353ecf52e/examples/DoReFa-Net/alexnet-dorefa.py#L37-L42

**Comment by csyhhu** [comment]
Hi @ppwwyyxx , it works, thanks for your help~!
